<!DOCTYPE html>
<html>
<head>
    <title>Image to GIF Conversion</title>
</head>
<body>
    <h1>Image to GIF Conversion</h1>
    <?php
    require 'vendor/autoload.php'; // Path to autoload file generated by Composer

    use Intervention\Image\ImageManagerStatic as Image;

    // Open the original image
    $image = Image::make('image.jpg');

    // Convert to GIF
    $image->encode('gif')->save('output.gif');

    echo '<p>Image converted to GIF using Intervention Image.</p>';
    ?>
    <img src="output.gif" alt="Converted GIF">
</body>
</html>
